name: main
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  terraform:
    if: github.event.pull_request.merged == true
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Unit Test
        run: npm run test:unit
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc_github_terraform
          aws-region: us-east-2
      - name: Terraform Init
        id: init
        run: |
          terraform -chdir=infastructure/base init
          terraform -chdir=infastructure/workload init
      
      - name: Terraform Apply - base
        id: apply_base
        run: terraform -chdir=infastructure/base apply -no-color -auto-approve

      - name: Terraform Apply - workload
        id: apply_workload
        run: |
          terraform -chdir=infastructure/workload apply -no-color -var="image_version=${{ github.event.pull_request.number }}" -auto-approve
     